src/semantic.zig

- enter/exit scopes when a block statement is encountered
- add docs to most internal semantic methods
- minor semantic cleanup

feat(semantic): enter block scopes

---

Justfile
build.zig
src/root.zig
src/semantic.zig
tasks/submodules.sh
test/README.md
test/TestSuite.zig
test/repos.json
test/semantic/ecosystem_coverage.zig
test/test_e2e.zig
test/utils.zig

Currently failing due to bugs in semantic analysis.

test: add e2e setup

---

.gitignore
Justfile
build.zig
tasks/init.sh

test: add testing with code coverage

---

.vscode/launch.json
src/semantic/SemanticBuilder.zig
test/semantic/ecosystem_coverage.zig
test/test_e2e.zig

Trying to re-enable ecosystem coverage tests. To do so, there's a bunch of bug fixing that needs to happen. This is the first of several bug-fixing PRs.

test(e2e): fixes towards re-enabling ecosystem coverage tests

---

.vscode/launch.json
.vscode/tasks.json
src/Error.zig
src/cmd/lint_command.zig
src/lint.zig
src/reporter/Reporter.zig
src/reporter/formatters/GraphicalFormatter.zig
src/reporter/formatters/GraphicalTheme.zig
src/reporter/formatters/Style.zig
src/reporter/formatters/styles/Color.zig
src/reporter/formatters/styles/control.zig
src/reporter/formatters/styles/styles.zig
src/source.zig
src/util.zig

This pr gets unicode/colored error formatting _mostly_ complete. It's functional, but missing several key pieces:
1. multiline spans aren't handled
2. label text not rendered
3. help text is still missing
4. URLs aren't rendered
That being said, it's starting to look pretty good.

feat(linter): graphical theme

---

src/linter/lint_context.zig
src/linter/rules/no_unresolved.zig

Also changes `diagnosticAlloc` into `diagnosticFmt`

fix(linter/no-unresolved): treat non-string imports as violations

---

.github/workflows/autofix.yaml
.github/workflows/ci.yaml
.github/workflows/codecov.yaml

the other one is no longer maintained.

ci: switch out setup zig task

---

src/cmd/lint_command.zig
src/reporter/Reporter.zig

_note: this was a debug build and therefore slower than it should be_

feat(linter): print summary statistics after linting

---

src/Error.zig
src/linter/lint_context.zig
src/linter/rules/homeless_try.zig
src/linter/rules/no_undefined.zig
src/linter/rules/no_unresolved.zig
src/linter/rules/snapshots/homeless-try.snap
src/reporter/formatters/GraphicalFormatter.zig
src/source.zig

Closes #80
- feat: GraphicalFormatter now renders help message and label text
- feat: add help message and label text to `homeless-try` lint rule.

feat: render help and labels

---

.typos.toml
src/linter/rule.zig
src/linter/rules.zig
src/linter/rules/no_catch_return.zig
src/linter/rules/snapshots/no-catch-return.snap

feat(linter): add `no-catch-return` rule

---

src/linter/rules/homeless_try.zig

```zig
fn add(a: u32, b: u32) u32 {
return a + b;
}
test add {
// not a violation
try std.testing.expectEqual(1, add(1, 1));
}
```

fix(linter/homeless-try): allow `try` in `test` statements

---

src/semantic/Reference.zig
src/semantic/SemanticBuilder.zig
src/semantic/test/symbol_ref_test.zig
test/snapshots/semantic-coverage/zig.snap
test/snapshots/snapshot-coverage/simple/pass/writer_interface.zig.snap

fix(semantic): bind type annotations on variable declarations

---

tasks/new-rule.ts

`just new-rule <rule-name>` now updates `RulesConfig`, adding a field for the new rule.

build: add new rules to `RulesConfig`

---

src/cli/Options.zig
src/cli/lint_command.zig
src/reporter/Reporter.zig

feat(cli): add `--no-summary` flag

---

test/repos.json
test/semantic/ecosystem_coverage.zig
test/snapshots/semantic-coverage/bun.snap
test/snapshots/semantic-coverage/ghostty.snap
test/snapshots/semantic-coverage/zig.snap

- update commit SHAs for `oven-sh/bun` and `ziglang/zig`
- add ghostty to ecosystem list
- better ecosystem printing for TTYs

chore: update ecosystem repo commit hashes, add ghostty

---

src/linter/linter.zig
src/linter/rule.zig
tasks/new-rule.ts

feat(linter): add hook to run a rule once per source file

---

src/linter/rules/homeless_try.zig

Fixes a false positive when using `try` in functions that directly return errors. This is kinda a hack because we don't have type checking.

fix(linter/homeless-try): false positive when returning errors

---

src/linter/rules/avoid_as.zig

fix(linter/avoid-as): fixer should not strip `pub` from vars

---

.typos.toml
src/cli/lint_command.zig
src/walk/glob.zig
src/walk/glob_test.zig

Closes #198
You can now specify files/folders to lint using a glob
```sh
zlint src/**
```

feat: allow specifying paths and globs in cli

---

.github/workflows/js.yaml
apps/vscode-extension/.gitignore
apps/vscode-extension/.vscodeignore
apps/vscode-extension/LICENSE
apps/vscode-extension/README.md
apps/vscode-extension/build.ts
apps/vscode-extension/bun.lock
apps/vscode-extension/package.json
apps/vscode-extension/src/BinaryService.ts
apps/vscode-extension/src/ConfigService.ts
apps/vscode-extension/src/DiagnosticsService.ts
apps/vscode-extension/src/extension.ts
apps/vscode-extension/src/util.ts
apps/vscode-extension/tsconfig.json
src/Error.zig
src/reporter/formatters/JSONFormatter.zig
src/span.zig

Add a vscode extension. I still need to publish it.
Note that current builds of `zlint` will not work with the extension. Only builds made on or after this commit will work b/c of changes made to json diagnostics
It sucks but it works. I'll make it progressively better.

feat: vscode extension

---

src/linter/rules/unused_decls.zig

When removing a variable declaration, if it takes up the entire line, remove the entire line instead of just the decl.

fix(linter/unused-decls): auto fixer removes newlines

---

src/linter/LintService.zig
src/span.zig

This makes error reporting 2-3x faster

perf(reporter): use SIMD when finding line and column numbers

---

apps/site/.gitignore
apps/site/src/pages/playground/index.tsx
apps/site/static/js/worker.js
build.zig
src/root_wasm.zig

Compile zlint to wasm and load in docusaurus page.
Bare minimum skeleton for @DonIsaac to finish

ZLint Playground Skeleton

---

build.zig.zon

Support being used as a dependency
