DonIsaac/zlint

.gitignore, src/cmd/print_command.zig, src/printer/Printer.zig, src/printer/SemanticPrinter.zig, src/semantic.zig
I also plan on using this for snapshot tests
=> feat(print): `--print-ast` prints symbol table

src/lint.zig, src/printer/SemanticPrinter.zig, src/semantic.zig, src/semantic/Semantic.zig, src/semantic/Symbol.zig, src/semantic/symbol.zig
- refactor: move `exports` and `members` lists from `SymbolTable` into `Symbol`
- refactor: make `Symbol` a top-level struct
- perf: use `MultiArrayList` to store symbols
- feat: add `Symbol.Iterator`
With this change, `members` and `exports` now belong to `Symbols` (which is better logically) without sacrificing the memory layout benefits of having an array of arrays.
=> perf(semantic): use SoA for `SymbolTable`

Justfile, build.zig
`just build -Dsingle-threaded`. Useful for getting stack traces while debugging.
=> build: support single-threaded builds

.github/workflows/ci.yaml, src/printer/SemanticPrinter.zig, src/semantic/Scope.zig, src/semantic/SemanticBuilder.zig, src/semantic/Symbol.zig, test/snapshots/snapshot-coverage/simple/pass/block.zig.snap, test/snapshots/snapshot-coverage/simple/pass/block_comptime.zig.snap, test/snapshots/snapshot-coverage/simple/pass/cond_if.zig.snap, test/snapshots/snapshot-coverage/simple/pass/enum_members.zig.snap, test/snapshots/snapshot-coverage/simple/pass/fibonacci.zig.snap, test/snapshots/snapshot-coverage/simple/pass/fn_comptime.zig.snap, test/snapshots/snapshot-coverage/simple/pass/fn_in_fn.zig.snap, test/snapshots/snapshot-coverage/simple/pass/foo.zig.snap, test/snapshots/snapshot-coverage/simple/pass/loops_for.zig.snap, test/snapshots/snapshot-coverage/simple/pass/loops_while.zig.snap, test/snapshots/snapshot-coverage/simple/pass/struct_members.zig.snap, test/snapshots/snapshot-coverage/simple/pass/top_level_struct.zig.snap, test/snapshots/snapshot-coverage/simple/pass/writer_interface.zig.snap
This data was already available in the symbol table (symbol -> scope). Now the reverse is also recorded (scope -> its symbols).
I also refactored `declareSymbol` et al to use named parameters. Makes setting defaults much easier.
=> feat(semantic): record bound symbols in scope tree

src/Error.zig, src/reporter/Reporter.zig, test/harness/TestSuite.zig
Only open a suite's snapshot file after all tests have run. Before, canceling a test in the middle of a run would leave the snapshot file empty, which is annoying.
=> test(e2e): open snapshot file after tests run

src/printer/SemanticPrinter.zig, src/semantic/SemanticBuilder.zig, src/semantic/Symbol.zig, src/semantic/id.zig
Only `Symbol.Id` is updated to use `NominalId`.
=> refactor: add nominal id types

src/printer/Printer.zig, src/printer/SemanticPrinter.zig, src/semantic/SemanticBuilder.zig, src/semantic/Symbol.zig, src/semantic/test/symbol_ref_test.zig, test/snapshots/snapshot-coverage/simple/pass/block.zig.snap, test/snapshots/snapshot-coverage/simple/pass/block_comptime.zig.snap, test/snapshots/snapshot-coverage/simple/pass/cond_if.zig.snap, test/snapshots/snapshot-coverage/simple/pass/enum_members.zig.snap, test/snapshots/snapshot-coverage/simple/pass/fibonacci.zig.snap, test/snapshots/snapshot-coverage/simple/pass/fn_comptime.zig.snap, test/snapshots/snapshot-coverage/simple/pass/fn_in_fn.zig.snap, test/snapshots/snapshot-coverage/simple/pass/foo.zig.snap, test/snapshots/snapshot-coverage/simple/pass/loops_for.zig.snap, test/snapshots/snapshot-coverage/simple/pass/loops_while.zig.snap, test/snapshots/snapshot-coverage/simple/pass/struct_members.zig.snap, test/snapshots/snapshot-coverage/simple/pass/top_level_struct.zig.snap, test/snapshots/snapshot-coverage/simple/pass/unresolved_import.zig.snap, test/snapshots/snapshot-coverage/simple/pass/writer_interface.zig.snap
- fix(semantic): bug when resolving references on scope exit causing references that occur before declarations to never be resolved. Caused by incorrect unresolved reference count, which in turn caused unresolved references to never be moved to parent stack frame.
- test(semantic): reference counting unit tests.
- fix(printer): better indenting when printing symbols and scopes.
=> fix(semantic): bugs in reference recording

src/semantic/SemanticBuilder.zig, src/semantic/Symbol.zig, src/semantic/test/symbol_decl_test.zig, src/semantic/test/symbol_ref_test.zig, src/semantic/test/util.zig, test/fixtures/simple/pass/cond_if.zig, test/snapshots/snapshot-coverage/simple/pass/cond_if.zig.snap, test/snapshots/snapshot-coverage/simple/pass/fn_comptime.zig.snap, test/snapshots/snapshot-coverage/simple/pass/loops_for.zig.snap, test/snapshots/snapshot-coverage/simple/pass/loops_while.zig.snap
`x` and `err` now get bound
```zig
const res: anyerror!u32 = 1;
if (res) |x| {
_ = x;
} else |err| {
_ = err;
}
```
Also adds `s_payload` symbol flag.
=> feat(semantic): bind if/else payloads

src/semantic/Symbol.zig, src/semantic/test/symbol_decl_test.zig, src/semantic/test/symbol_ref_test.zig
This pull request includes several changes to the `src/semantic` module, primarily focusing on improving the handling of symbol flags and references in tests. The most important changes include adding new test cases for symbol flags, updating existing tests to include reference flags, and minor documentation updates.
* [`src/semantic/test/symbol_decl_test.zig`](diffhunk://#diff-f57bb59ba688c57d254ac7ed57d2f194260c838815feaddaa2331c0b4ab67eb6R12-R60): Added a new test `test "Symbol flags for various declarations of 'x'"` to verify symbol flags for different declarations.
* [`src/semantic/test/symbol_ref_test.zig`](diffhunk://#diff-3d643eef507057efb89c60651dc83a9e309e7b4bfa04b20c09d1edb42cb5593cL58-R77): Updated the `test "simple references where `x` is referenced a single time"` to include …
=> test(semantic): symbol and reference flag unit tests

src/linter.zig, src/linter/lint_context.zig, src/linter/rule.zig, src/linter/rules/no_undefined.zig, src/linter/rules/no_unresolved.zig, src/linter/tester.zig, tasks/new-rule.ts
This pull request introduces significant changes to the `Rule` struct and its usage across various files in the linter module. The primary change involves replacing the `name` field in `Rule` with a `meta` field that includes additional metadata such as `name`, `category`, and a `default` flag. This update necessitated modifications in several files to accommodate the new `meta` structure.
Key changes include:
* [`src/linter/rule.zig`](diffhunk://#diff-c1081df3f33f9211b84196d844bcbec110d72cd83888108a4131268684723c48L36-R54): Replaced `name` field with `meta` field in `Rule` struct and added `Meta` and `Category` sub-structs to encapsulate rule metadata. [[1]](diffhunk://#diff-c1081df3f33f9211b84196d844bcbec110d72cd83888108a4131268684723c48L36-R54) …
=> feat(linter): generalize rule metadata

src/linter/rules.zig, src/semantic/Scope.zig, src/semantic/SemanticBuilder.zig, src/semantic/Symbol.zig, src/semantic/test/symbol_ref_test.zig, test/snapshots/snapshot-coverage/simple/pass/block.zig.snap, test/snapshots/snapshot-coverage/simple/pass/cond_if.zig.snap, test/snapshots/snapshot-coverage/simple/pass/enum_members.zig.snap, test/snapshots/snapshot-coverage/simple/pass/fibonacci.zig.snap, test/snapshots/snapshot-coverage/simple/pass/fn_comptime.zig.snap, test/snapshots/snapshot-coverage/simple/pass/fn_in_fn.zig.snap, test/snapshots/snapshot-coverage/simple/pass/foo.zig.snap, test/snapshots/snapshot-coverage/simple/pass/loops_for.zig.snap, test/snapshots/snapshot-coverage/simple/pass/loops_while.zig.snap, test/snapshots/snapshot-coverage/simple/pass/top_level_struct.zig.snap, test/snapshots/snapshot-coverage/simple/pass/writer_interface.zig.snap
- feat: add and populate `Scope.node`. It stores the ID of the AST node that creates it.
- fix: function bodies create two scopes for the same block node.
- feat: record flags to apply on the next-encountered block scope
=> feat(semantic): link scopes to the nodes that create them

src/linter/lint_context.zig, src/linter/rules.zig, src/linter/rules/homeless_try.zig, src/linter/rules/snapshots/homeless-try.snap, src/linter/tester.zig, src/semantic/Scope.zig, src/semantic/SemanticBuilder.zig, test/snapshots/snapshot-coverage/simple/pass/enum_members.zig.snap, test/snapshots/snapshot-coverage/simple/pass/fn_comptime.zig.snap, test/snapshots/snapshot-coverage/simple/pass/fn_in_fn.zig.snap, test/snapshots/snapshot-coverage/simple/pass/foo.zig.snap, test/snapshots/snapshot-coverage/simple/pass/struct_members.zig.snap, test/snapshots/snapshot-coverage/simple/pass/writer_interface.zig.snap
`homeless-try` looks for `try` used outside of error union-returning functions.
Part of #3
=> feat(linter): add `homeless-try` lint rule

src/semantic/Scope.zig, src/semantic/SemanticBuilder.zig, src/semantic/Symbol.zig, src/semantic/test/symbol_decl_test.zig, test/snapshots/snapshot-coverage/simple/pass/container_error.zig.snap, test/snapshots/snapshot-coverage/simple/pass/enum_members.zig.snap, test/snapshots/snapshot-coverage/simple/pass/fn_comptime.zig.snap, test/snapshots/snapshot-coverage/simple/pass/fn_in_fn.zig.snap, test/snapshots/snapshot-coverage/simple/pass/foo.zig.snap, test/snapshots/snapshot-coverage/simple/pass/struct_members.zig.snap, test/snapshots/snapshot-coverage/simple/pass/writer_interface.zig.snap
This pull request introduces several changes to improve flag handling and container symbol management in the `semantic` module. The changes include adding new flag types, modifying flag management methods, and updating various test cases to reflect these changes.
* [`src/semantic/Scope.zig`](diffhunk://#diff-958d614f60e8a4dd6e7a624a5f2f9cfe400d23ebaf269ea7b3d3a483346f7594R58-R68): Added a new method `set` to the `Flags` struct to enable or disable specific flags.
* [`src/semantic/Symbol.zig`](diffhunk://#diff-ce5dcdaa242de029c9f716f363245d575bbd751ee3dc8fc2b857860aa2b4b20bL70-R71): Introduced new flags (`s_struct`, `s_enum`, `s_union`) and a `merge` method to combine flags. [[1]](diffhunk://#diff-ce5dcdaa242de029c9f716f363245d575bbd751ee3dc8fc2b857860aa2b4b20bL70-R71) …
=> feat(semantic): add container symbol flags

build.zig, src/semantic/SemanticBuilder.zig
Closes #118
Caused by `util.assertUnchecked`. This is a very funky error since the assertion does not fail in debug builds when processing the same files.
I also added a `-Ddebug-release` flag for creating release builds with symbols and error traces.
=> fix(semantic): out-of-bounds index access in release builds

src/semantic/SemanticBuilder.zig, src/semantic/test/symbol_decl_test.zig, src/semantic/test/symbol_ref_test.zig, test/snapshots/snapshot-coverage/simple/pass/fn_comptime.zig.snap, test/snapshots/snapshot-coverage/simple/pass/top_level_struct.zig.snap, test/snapshots/snapshot-coverage/simple/pass/writer_interface.zig.snap
Part of #42 
- fix: visit return types in function declarations
- fix: add `type` reference flags to returned identifiers
- fix: return types are in same scope as the rest of the function's prototype
- fix: simple function prototype nodes not being visited
=> fix(semantic): binding function return types

src/cli/Options.zig, src/cli/lint_command.zig, src/reporter.zig, src/reporter/Reporter.zig
`-q,--quiet` suppresses all non error-level diagnostics. They're still recorded and shown in the stats summary, but their descriptions aren't rendered.
=> feat: add `--quiet` cli flag

Justfile, src/semantic/SemanticBuilder.zig
for some reason where `flags` is declared in `visitContainerFields` matters? If it's at the top, it points to memory outside any of zlint's segments...
=> fix(semantic): segfault in release builds

docs/rules/suppressed-errors.md, src/semantic/SemanticBuilder.zig, src/semantic/test/symbol_ref_test.zig, test/snapshots/snapshot-coverage/simple/pass/loops_while.zig.snap, test/snapshots/snapshot-coverage/simple/pass/top_level_struct.zig.snap
```zig
const Foo = struct {};
const foo = Foo{};
//          ^^^
```
=> fix(semantic): bind type identifiers in struct initialization nodes

src/Error.zig, src/cli/Options.zig, src/cli/lint_command.zig, src/linter.zig, src/linter/tester.zig, src/reporter.zig, src/reporter/Reporter.zig, src/reporter/formatter.zig, src/reporter/formatters/GithubFormatter.zig, src/reporter/formatters/GraphicalFormatter.zig, src/semantic/test/util.zig, test/semantic/snapshot_coverage.zig
ZLint can now print error messages using GitHub Action's annotation log format. Run `zlint --format github` in your CI and any problems found will be attached as reviews on your PR.
- feat(report): add `GithubFormater`
- feat(cli): add `-f,--format` flag to choose a formatter. Defaults to `default` (graphical formatter)
- refactor(report): Reporter takes runtime-known formatters
Formatters can no longer be specified at comptime since `-f,--format` is runtime known.
=> feat(reporter): add github formatter

src/linter/lint_context.zig, src/linter/rules/homeless_try.zig, src/linter/rules/no_catch_return.zig, src/linter/rules/no_unresolved.zig, src/semantic/Semantic.zig, src/semantic/SemanticBuilder.zig, src/semantic/ast.zig
Lex and store tokens in `Semantic`. This prevents constant re-lexing with `ast.tokenSlice`.
=> perf(semantic): store tokens in `Semantic`

docs/rules/no-return-try.md, src/linter/config/rules_config.zig, src/linter/rules.zig, src/linter/rules/no_return_try.zig, src/linter/rules/snapshots/no-return-try.snap
Disallow returning a `try` expression. Code should return error unions directly.
```zig
fn foo() !void { return; }
fn bar() !void { return try foo(); }
```
=> feat(linter): add `no-return-try` rule

src/semantic/Semantic.zig, src/semantic/SemanticBuilder.zig, src/semantic/ast.zig, src/semantic/tokenizer.zig, src/span.zig
Extract comments (both doc comments and "normal" comments) from source code during tokinization pass. Comments will be used to extract disable directives in a later PR.
- refactor: move `tokenize` into separate file
- feat: extract comments otherwise ignored by `std.zig.Tokenizer` during tokenization pass
- perf: record number of `.identifier` tokens seen during tokenization pass and use it to pre-allocate memory for symbol table
=> feat: extract comments from source

src/reporter/Reporter.zig, src/reporter/formatter.zig, src/reporter/formatters/GithubFormatter.zig, src/reporter/formatters/GraphicalFormatter.zig
Only report summary statistics when reporting diagnostics with the graphical reporter. This will make CI runs with the github actions formatter cleaner.
=> fix(reporter): only report summary stats for graphical format

src/cli/Options.zig, src/cli/lint_command.zig
Adds a `-S, --stdin` flag for reading paths from stdin, instead of recursively walking the current working directory. ZLint expects one filepath per line and, if relative, paths must be relative to the cwd.
Only lint modified files before committing.
```sh
git diff --name-only | zlint --stdin
```
Only lint files modified by your PR (useful for CI checks)
```sh
git diff HEAD..origin/main --name-only | zlint --stdin
```
=> feat(cli): add `--stdin` for reading paths to lint

src/linter.zig, src/linter/disable_directives.zig, src/linter/disable_directives/Comment.zig, src/linter/disable_directives/Parser.zig, src/linter/disable_directives/Parser_test.zig, src/span.zig
Parse disable directives from regular and doc comments. A follow-up PR will update the linter to check for disabled rules and suppress diagnostics accordingly.
=> feat(linter): parse disable directives

src/linter/rule.zig, src/linter/rules/unused_decls.zig, src/linter/tester.zig, src/semantic/Reference.zig, src/semantic/Scope.zig, src/semantic/Symbol.zig, src/semantic/ast.zig, src/util.zig, src/util/id.zig
Adds `Rule.Id`, a nominal identifier type with a `u32` representation. All rules have a unique `Rule.Id` assigned at comptime. This is for quick rule equality checks.
- refactor: move `NominalId` from `semantic` to `util`
- refactor: add `Rule.Id`
- refactor: add comptime mapper of rule names -> `Rule.Id`
=> refactor(linter): give rules a unique numeric ID

src/linter.zig, src/linter/RuleSet.zig, src/linter/disable_directives/Comment.zig, src/linter/rule.zig, src/linter/test/disabling_rules_test.zig, src/semantic/Semantic.zig
This pull request introduces several enhancements and refactorings to the linter functionality in the Zig programming language. The most significant changes include adding support for disable directives, improving the rule filtering mechanism, and adding comprehensive tests for the new features.
* Added support for disable directives to the linter, allowing specific rules to be disabled globally or locally in the source code. (`src/linter.zig`, `src/linter/disable_directives.zig`, `src/linter/disable_directives/Comment.zig`) [[1]](diffhunk://#diff-3cf1e7358964b262694db62ec01170f62e059713cfff9d24f3d888d08cc02df9R8) [[2]](diffhunk://#diff-3cf1e7358964b262694db62ec01170f62e059713cfff9d24f3d888d08cc02df9L31) [[3]](diffhunk://#diff-3cf1e7358964b262694db62ec01170f62e059713cfff9d24f3d888d08cc02df …
=> feat(linter): support global disable directives

docs/rules/no-undefined.md, src/linter/rules/no_undefined.zig, src/linter/rules/snapshots/no-undefined.snap, src/semantic/NodeLinks.zig
This will no longer be a violation, due to how common `@memset` and `@memcpy` initializations are:
```zig
const x: [1]u8 = undefined;
```
=> feat(linter/no-undefined): allow undefined-initialized arrays

docs/rules/homeless-try.md, src/linter/rules/homeless_try.zig
Allow `try` in non-root `comptime` scopes.
```zig
fn foo(x: u32) void {
comptime {
try bar(x);
}
}
fn bar(x: u32) !void {
if (x == 0) {
return error.Unreachable;
}
}
test {
foo(1);
}
```
=> fix(linter/homeless-try): allow `try` in comptime blocks

src/cli/lint_command.zig, src/cli/lint_config.zig, src/linter.zig, src/linter/Config.zig, src/linter/test/disabling_rules_test.zig, test/fixtures/config/zlint.json
- Fix resolve config test to actually resolve zlint.json and test that it does so
- fix a memory leak caused by moving an arena and only deiniting it in the outer scope
- arena wasn't even used in the outer scope so pushed it down into the lower scope
- removed a comment that I have some questions about @DonIsaac
=> Fix `resolveLintConfig` test and bad arena move causing leak

src/cli/Options.zig, src/cli/lint_command.zig, src/linter.zig, src/linter/fix.zig, src/linter/lint_context.zig, src/linter/rule.zig, src/linter/rules/homeless_try.zig, src/linter/rules/no_catch_return.zig, src/linter/rules/no_return_try.zig, src/linter/rules/no_undefined.zig, src/linter/rules/no_unresolved.zig, src/linter/rules/snapshots/homeless-try.snap, src/linter/rules/suppressed_errors.zig, src/linter/rules/unused_decls.zig, src/linter/test/fix_test.zig, src/semantic/Semantic.zig, src/source.zig, src/span.zig
Part of #183.
Adds automatic fixing capabilities. Lint rules may now provide a fixer function when they report an error that, when applied to the linted source, will fix the violation that was found.
This PR also adds an auto-fixer to `no-catch-return`.
- Testing infrastructure will be added in a follow-up pr. It is blocked by the upcoming LintService refactor
- Rule docgen still needs to be updated to include fix info in rule documentation. Again, will be added in an upcoming PR.
=> feat(linter): auto-fix lint rule violations with `--fix`

src/linter.zig, src/linter/disable_directives/Parser.zig, src/linter/disable_directives/Parser_test.zig, src/linter/test/disabling_rules_test.zig
👋 hey there, thanks for creating this! i did a quick search and didnt see this come up in any issues, but apologies if I missed something. 
I've got a test file I wanted to do some ignores on like:
```zig
// zlint-disable suppressed-errors, no-undefined
// imports
```
it seemed like only one of the directives was being picked up -- I tried with and without commas. so I took a look.
I added a simple test following the pattern of existing tests and the test failed, so did some poking around and made a few tweaks. `just test` and `just e2e` all seems happy so I think/hope I didnt break anything here 😄 
Changes:
- added test to assert multiple global directives are picked up
- in Parser modified the current cursor position check parse method to select the min of itself or end of the span …
=> fix(linter): multiple file level directives

src/linter/rules/no_undefined.zig, src/linter/rules/snapshots/no-undefined.snap
Explicitly ban `undefined` in all comparisons, even if a safety comment is present.
```zig
fn foo(bar: *Bar) void {
// this is never safe
if (bar == undefined) {}
}
```
=> feat(linter/no-undefined): check for undefined in comparisons

src/linter/rules/no_unresolved.zig, src/linter/rules/snapshots/no-unresolved.snap
Add a label telling users if they're importing a missing file or a directory.
```
𝙭 no-unresolved: Unresolved import to 'does-not-exist.zig'
╭─[src/no-unresolved.zig:1:19]
1 │ const x = @import("does-not-exist.zig");
·                   ───────────┬───────────
·                              ╰── file 'does-not-exist.zig' does not exist
╰────
```
=> feat(linter/no-unresolved): inform on missing file vs directory imports

docs/rules/suppressed-errors.md, src/linter/rules/snapshots/suppressed-errors.snap, src/linter/rules/suppressed_errors.zig, src/semantic/NodeLinks.zig
Allow suppressing errors when calling `Writer` methods
```zig
writer.print("foo\n", .{}) catch {};
writer.print("foo\n", .{}) catch unreachable;
```
=> feat(linter/suppressed-errors): allow suppressions on writer methods

src/Error.zig, src/cli/lint_command.zig, src/cli/lint_config.zig, src/linter/config/rules_config.zig, src/span.zig, src/util.zig, src/util/cow.zig
Closes #206.
Zlint now prints an error and exits with a failure code when a `zlint.json` config contains rules that do not exist.
=> feat(linter): report configs with unknown rules

Justfile, docs/rules/must-return-ref.md, src/linter/ast_utils.zig, src/linter/config/rules_config.zig, src/linter/rules.zig, src/linter/rules/must_return_ref.zig, src/linter/rules/snapshots/must-return-ref.snap, src/visit/walk.zig, src/visit/walk_test.zig, tasks/gen_utils.zig, tasks/new-rule.ts
Adds a new rule that checks for list/allocator typed properties returned by value instead of by reference.
```zig
pub const Foo = struct {
list: std.ArrayList(u32),
pub fn getList(self: *Foo) std.ArrayList(u32) {
return self.list;
}
};
pub fn main() !void {
var foo: Foo = .{
.list = try std.ArrayList(u32).init(std.heap.page_allocator)
};
defer foo.list.deinit();
var list = foo.getList();
try list.append(1); // leaked!
}
```
=> feat(linter): add `must-return-ref` rule

src/linter/rules/homeless_try.zig, src/linter/rules/snapshots/homeless-try.snap
Handle functions that may or may not return an error union.
```zig
pub fn push(list: std.ArrayList(u32), x: u32, comptime assume_capacity: bool) if(assume_capacity) void else Allocator.Error!void {
if (comptime assume_capacity) {
list.appendAssumeCapacity(x);
} else {
try list.append(x);
}
}
```
=> fix(linter/homeless-try): handle `if` in fn return type

docs/rules/suppressed-errors.md, src/linter/ast_utils.zig, src/linter/rules/suppressed_errors.zig
This is no longer a `suppressed-errors` violation:
```zig
test bar {
bar(1) catch {};
}
```
=> fix(linter/suppressed-errors): allow suppression in test blocks

src/cli/Options.zig, src/cli/lint_command.zig, src/lint.zig, src/linter/LintService.zig
Adds a `--fix-dangerously` CLI flag to enable possibly breaking auto fixes. This currently has no effect (outside of normal `--fix` behavior) and will not do anything until I implement dangerous fixers for some rules.
=> feat(cli): add CLI flag to apply dangerous fixes

src/cli/Options.zig, src/linter/LintService.zig, src/linter/fix.zig, src/linter/linter.zig, src/linter/rules/no_catch_return.zig, src/linter/rules/unused_decls.zig, src/linter/test/fix_test.zig, src/linter/tester.zig
After this PR is merged, `zlint --fix-dangerously` will automatically delete all unused top-level variable declarations 🎊
=> feat(linter): add dangerous auto fixer for `unused-decls`

src/semantic/SemanticBuilder.zig, src/semantic/test/symbol_decl_test.zig, src/semantic/test/symbol_ref_test.zig
This PR has two fixes in it.
First, record identifier references for containers that specify a backing representation.
```zig
const Foo = packed struct (u32) { };
//                         ^^^
const Tag = enum { a, b };
const Bar = union(Tag) { a: void, b: u32 };
//                ^^^
const Baz = enum(u8) { a, b };
//               ^^
```
Second, add `.s_extern` to symbol flags for extern unions and structs. extern enums aren't allowed by Zig, but for now they still get `.s_extern`.
=> fix(sema): handle container layouts

src/linter/lint_context.zig, src/linter/rules/unused_decls.zig
`ast.nodeToSpan` truncates spans for nodes that cover more than one line. Not sure why they do that, but it breaks our code. We should replace all usages of it tbh.
=> fix: spans over multi-line nodes

src/linter/rules/unused_decls.zig, src/semantic/Semantic.zig, src/semantic/SemanticBuilder.zig, src/semantic/test/symbol_ref_test.zig
Fixes a bug where references to identifiers were being resolved to container members in cases of name collision
```zig
const T = u32;
const Foo = union(enum) {
T: T, // <- annotation was resolving to declared union member
};
```
=> fix(sema): container field/variable name collisions

src/main.zig, test/harness/runner.zig
Use the new `SmpAllocator` in release builds. Gives us another 17% perf bump
=> perf: use SmpAllocator

src/reporter/Reporter.zig, src/reporter/StringWriter.zig
This reduces write contention on stdout lock by letting linting threads format in parallel before blocking to write. Brings average reporting times when running on Bun from ~800ms to ~500ms.
=> perf: format to string before writing

src/cli/lint_command.zig, src/cli/lint_config.zig, src/linter/Config.zig, zlint.schema.json
Support ignoring files and folders via `zlint.json`. I've also added a JSON schema file to make life a little better.
```json
{
"$schema": "./zlint.schema.json",
"ignore": ["test/fixtures"],
"rules": {
"unused-decls": "warn"
}
}
```
=> feat(linter): configure ignored folders

src/linter/rules/unsafe_undefined.zig, src/semantic/NodeLinks.zig, src/semantic/SemanticBuilder.zig
Closes #242, supersedes #254
This also adds identifier tokens -> symbol declarations in `NodeLinks`
=> fix(linter/unsafe-undefined): false positive for enum variants named `undefined`

src/linter/rules/homeless_try.zig, src/semantic/SemanticBuilder.zig
closes #258
We needed to change how `continue` nodes got visited, since both lhs and rhs are now used in zig 0.14
=> fix(linter/homeless-try): false positive in labeled continues

docs/rules/avoid-as.md, src/linter/config/rules_config.zig, src/linter/rules.zig, src/linter/rules/avoid_as.zig, src/linter/rules/snapshots/avoid-as.snap, src/span.zig
> AI generated bc im feeling lazy
This pull request introduces a new linting rule to disallow the use of `@as()` when types can be inferred, along with the necessary changes to integrate this rule into the existing system.
* Added a new rule `avoid-as` that disallows the use of `@as()` when types can be inferred. This rule is categorized as `pedantic` and is enabled by default as a warning. [[1]](diffhunk://#diff-eca5dc407c141ea5b0c0e57df9f7d5d859bb57158b92836db34c1cfa214aabe4R1-R42) [[2]](diffhunk://#diff-f0b74904761a925e1f9e35ab917c5a2eaf91b7afeb7673e69a854fbd3b62b47eR1-R201)
* Updated `rules_config.zig` to include the new `avoid-as` rule in the `RulesConfig` struct.
* Updated `rules.zig` to import the new `avoid_as.zig` file.
* Added a snapshot file `avoid-as.snap` for the new rule to …
=> feat(linter): add `avoid-as` rule

src/cli/lint_command.zig, src/linter/fix.zig, src/linter/lint_context.zig, src/linter/rules/unused_decls.zig, src/linter/test/lint_context_test.zig
Dangerous fixes were being run and applied when users ran `zlint --fix`.
=> fix(linter): `--fix` should not apply dangerous fixes

src/cli/print_command.zig, src/linter/LintService.zig, src/linter/lint_context.zig, src/linter/test/disabling_rules_test.zig, src/linter/test/lint_context_test.zig, src/linter/tester.zig, src/printer/SemanticPrinter.zig, src/semantic.zig, src/semantic/Scope.zig, src/semantic/Semantic.zig, src/semantic/SemanticBuilder.zig, src/semantic/Symbol.zig, src/semantic/test/util.zig, test/semantic/ecosystem_coverage.zig, test/semantic/snapshot_coverage.zig
* `SymbolTable` -> `Symbol.Table`
* `ScopeTree` -> `Scope.Tree`
* `SemanticBuilder` -> `Semantic.Builder`
=> refactor(sema): make better use of namespaces

src/linter/fix.zig, src/linter/rules/avoid_as.zig
Fixes a bug in `avoid-as`'s auto fixer where multi-line arguments to `@as()` were not handled properly
```zig
// this now fixes properly
const x = @as(u32, switch (some_comptime_enum) {
.foo => 1,
.bar => 2,
else => 3,
});
// into this:
const x: u32 = switch (some_comptime_enum) {
.foo => 1,
.bar => 2,
else => 3,
};
```
=> fix(linter/avoid-as): auto fixer on multi-line @as() args

src/linter/fix.zig, src/linter/rules/must_return_ref.zig, src/semantic/Semantic.zig, src/visit/walk.zig
Fixes a bunch of false positives in `must-return-ref`
=> fix(must-return-ref): only walk subtree of target function

docs/rules/unsafe-undefined.md, src/linter/rule.zig, src/linter/rules/snapshots/unsafe-undefined.snap, src/linter/rules/unsafe_undefined.zig, src/semantic/Semantic.zig
Allow whitelisting specific types which may be `undefined`. By default `std.Thread.Pool` is ignored.
```zig
fn main() !void {
var pool: std.Thread.Pool = undefined;
try pool.init(.{ .allocator = std.heap.page_allocator }); // now allowed
}
```
=> feat(linter/unsafe-undefined): allow ignoring certain types

apps/site/static/js/worker.js, src/root_wasm.zig
- forgot to pass length to free and JS didn't care, so it wasn't freeing
- removed stupid DST in favor of static transfer global
=> fix leak in playground wasm interop
